### ISSUE TITLE
`Plugins` -> `SENinja` -> `Start symbolic execution` results in `RuntimeError`

### ISSUE THREAD

**Issue by alexrp** [borzacchiello/seninja#11]
```text
Traceback (most recent call last):
  File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 129, in _address_action
    action(view_obj, addr)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\repositories\community\plugins\borzacchiello_seninja\apis_ui.py", line 150, in _async_start_se
    initialize_ui()
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\repositories\community\plugins\borzacchiello_seninja\apis_ui.py", line 112, in initialize_ui
    ui_set_arch(globs.executor.arch, globs.executor.state)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\repositories\community\plugins\borzacchiello_seninja\ui\__init__.py", line 132, in ui_set_arch
    BNWidgets.RW.init(arch, state)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\repositories\community\plugins\borzacchiello_seninja\ui\registers_view.py", line 92, in init
    self.tab_name = _normalize_tab_name(self.parent.getTabName())
RuntimeError: Internal C++ object (binaryninjaui.ViewFrame) already deleted.
```

**Comment by borzacchiello** [comment]
Hello!
Thank you for reporting the issue and sorry for the *very late* response.

The last commits should have fixed most of these UI crashes, but let me know if you encounter more! :)
