### ISSUE TITLE
Exception: Not enough space in stack. Increase stack size

### ISSUE THREAD

**Issue by b1gcat** [borzacchiello/seninja#12]
[keygenme4.exe.zip](https://github.com/borzacchiello/seninja/files/14004609/keygenme4.exe.zip)

i increate the stack size into 99, and it still says: not enough

can anyone help?

```
[Default] loading segments...
[Default] <segment: 0x400000-0x400200, r--> 0x400000 -> 0x200
[Default] <segment: 0x401000-0x41b118, r-x> 0x401000 -> 0x1a118
[Default] <segment: 0x41c000-0x41cc80, rw-> 0x41c000 -> 0x400
[Default] <segment: 0x41cc80-0x41cca0, ---> 0x41cc80 -> 0x0
[Default] remapping the same page '0x839'
[Default] <segment: 0x41cca0-0x41ccb4, ---> 0x41cca0 -> 0x0
[Default] remapping the same page '0x839'
[Default] loading finished!
[Default] ERROR: not enough space in stack. Increase stack size
[Default] Exception in thread Thread-2:
[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/Resources/bundled-python3/lib/python310.zip/threading.py", line 1016, in _bootstrap_inner
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 928, in run
[Default]     self.task.run()
[Default]   File "/Users/b1gcat/Library/Application Support/Binary Ninja/repositories/community/plugins/borzacchiello_seninja/apis_ui.py", line 52, in run
[Default]     self.callback(self)
[Default]   File "/Users/b1gcat/Library/Application Support/Binary Ninja/repositories/community/plugins/borzacchiello_seninja/apis_ui.py", line 123, in f
[Default]     globs.executor = SymbolicExecutor(bv, address)
[Default]   File "/Users/b1gcat/Library/Application Support/Binary Ninja/repositories/community/plugins/borzacchiello_seninja/sym_executor.py", line 142, in __init__
[Default]     raise Exception(
[Default] Exception: Not enough space in stack. Increase stack size
[Default] seninja not running

```

**Comment by borzacchiello** [comment]
Hello!
Thank you for reporting the issue.

The analysis of BinaryNinja created a stack variable with an enormous offset with respect to esp.
I changed a little bit the way in which stack is initialized. Now you should be able to create the initial state. Let me know!

**Comment by b1gcat** [comment]
> Hello! Thank you for reporting the issue.
> 
> The analysis of BinaryNinja created a stack variable with an enormous offset with respect to esp. I changed a little bit the way in which stack is initialized. Now you should be able to create the initial state. Let me know!

it works perfectly! thanks
